avoid celery getting into a weird db state
been seeing errors like this:
```
_revalidate_connection "Can't reconnect until invalid " sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
```

and like this:
```
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back
```

this happens if there's some error in a celery task. this breaks mysql
in that worker forever (because workers only initialize the DB once, at
startup).

we add a hook to auto-roll back the session if there's an error in the
task, or auto-commit it if there's no error, and then remove the session
no matter what at the end of the task. this allows our workers to
continue processing tasks even if something goes wrong with one of them.